'use client';
import {useCallback,useEffect,useState} from 'react';
type Passenger={id:string;nombre:string;telefono:string;registrado_at:string};
type Trip={id:string;pasajero_id:string;origen:string;destino:string;conductor:string|null;estado:string;precio_acordado:number|null};
export default function SharedRecords(){
 const [password,setPassword]=useState('');
 const [records,setRecords]=useState<{passengers:Passenger[];trips:Trip[]}|null>(null);
 const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!password)return;try{const res=await fetch('/api/admin/records',{headers:{'x-mooni-admin-password':password},cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'No se pudo cargar');setRecords(data);setError('');}catch(e){setError(e instanceof Error?e.message:'Error');setRecords(null)}},[password]);
 useEffect(()=>{if(!records)return;const timer=window.setInterval(refresh,8000);return ()=>window.clearInterval(timer)},[refresh,records]);
 return <section className="bg-gray-900 border border-white/10 p-5 rounded-xl space-y-4"><h2 className="font-bold text-xl">Panel compartido</h2><p className="text-sm text-gray-400">Cuando Supabase esté conectado, aquí aparecerán los registros de todos los dispositivos. La clave se conserva solo durante esta sesión de la página.</p><div className="flex flex-wrap gap-2"><input type="password" aria-label="Clave del panel compartido" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Clave de administración" className="bg-black border border-gray-700 rounded p-2"/><button onClick={refresh} className="bg-emerald-600 rounded px-4">Consultar registros</button></div>{error&&<p role="alert" className="text-amber-300">{error}</p>}{records&&<><p>{records.passengers.length} pasajeros · {records.trips.length} viajes (últimos 200)</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Nombre','Teléfono','Viaje','Ruta','Conductor','Estado','Acordado'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{records.trips.map(t=>{const p=records.passengers.find(x=>x.id===t.pasajero_id);return <tr key={t.id} className="border-t border-white/10"><td className="p-2">{p?.nombre||'—'}</td><td className="p-2">{p?.telefono||'—'}</td><td className="p-2">{t.id}</td><td className="p-2">{t.origen} → {t.destino}</td><td className="p-2">{t.conductor||'—'}</td><td className="p-2">{t.estado}</td><td className="p-2">{t.precio_acordado===null?'—':`$${Number(t.precio_acordado).toFixed(2)}`}</td></tr>})}</tbody></table></div><h3 className="font-semibold">Registrados sin viaje</h3><ul className="text-sm text-gray-300">{records.passengers.filter(p=>!records.trips.some(t=>t.pasajero_id===p.id)).map(p=><li key={p.id}>{p.nombre} · {p.telefono}</li>)}</ul></>}</section>
}
